name: MSBuild

on:
  push:
    branches:
      - master
      - develop
    release:
      types: [ prereleased, released]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: リポジトリのチェックアウト
        uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1
      - name: nugetのインストール
        uses: nuget/setup-nuget@v1
      - name: submoduleのnugetパッケージインストール
        run: nuget restore ./TTSController/src/vsCodeTalkerLanguageServer.sln
      - name: submoduleのビルド
        run: |
          msbuild ./TTSController/src/vsCodeTalkerLanguageServer.sln /t:build /p:configuration=release /p:platform="x64"
      - name: 本体のnugetパッケージインストール
        run: nuget restore vsCodeTalkerLanguageServer.sln
      - name: 本体のmsbuildの実行
        run: |
          msbuild vsCodeTalkerLanguageServer.sln /t:build /p:configuration=release /p:platform="x64"
      - name: ビルド内容を保存
        uses: actions/upload-artifact@v3
        with: 
          name: SpeechGRpcServer
          path: ./SpeechGRpcServer/bin/x64/Release/net48/*